version: "3.9"

services:
  python-app:
    image: python:3.11-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - ./:/app:rw
    env_file:
      - .env
    command: >
      sh -c "pip install -r requirements.txt && tail -f /dev/null"
